package github.chorman0773.pokemonsms.core;

public enum EnumType {
 NORMAL, GRASS, FIRE, WATER, ELECTRIC, GROUND, FLYING, ROCK,
 FIGHTING, POISON, PSYCHIC, GHOST, DARK, STEEL, ICE, DRAGON, FAIRY,
 SOLAR, LUNAR, CELESTIAL, TYPELESS, CHAOTIC, CATASTROPHE
}
